# Generated by Django 5.0.6 on 2024-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
