# Generated by Django 5.0.6 on 2024-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_memberuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='member_type',
            field=models.CharField(choices=[('PEM', 'premium'), ('REG', 'regular')], default='REG', max_length=3),
            preserve_default=False,
        ),
    ]
