# Generated by Django 5.0.7 on 2024-07-30 09:57

import Users.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_memberuser_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(choices=Users.constants.get_choices, max_length=1),
        ),
        migrations.AlterField(
            model_name='librarianuser',
            name='gender',
            field=models.CharField(choices=Users.constants.get_choices, max_length=1),
        ),
        migrations.AlterField(
            model_name='memberuser',
            name='gender',
            field=models.CharField(choices=Users.constants.get_choices, max_length=1),
        ),
    ]
