# Generated by Django 5.0.6 on 2024-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymodel',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
