# Generated by Django 5.0.6 on 2024-07-19 09:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_librarymodel_avaliable'),
        ('Users', '0003_memberuser_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime(2024, 7, 19, 9, 3, 44, 850236, tzinfo=datetime.timezone.utc))),
                ('return_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.librarymodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.memberuser')),
            ],
        ),
    ]
