# Generated by Django 5.0.6 on 2024-07-19 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 19, 9, 5, 48, 89232)),
        ),
    ]
